header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: AMPEL360 Project Contributors
    
  paths:
    - "**/*.py"
    - "**/*.js"
    - "**/*.ts"
    - "**/*.sh"
    - "**/*.yml"
    - "**/*.yaml"
  
  excludes:
    # Exclude generated reports and outputs
    - "cd/reports/**"
    - "cd/baselines/**"
    - "cd/costs/**"
    
    # Exclude documentation
    - "**/*.md"
    - "**/*.txt"
    - "**/*.rst"
    
    # Exclude configuration files
    - "**/.git/**"
    - "**/.github/**/*.md"
    - "**/node_modules/**"
    - "**/venv/**"
    - "**/__pycache__/**"
    - "**/*.pyc"
    
    # Exclude data files
    - "**/*.json"
    - "**/*.csv"
    - "**/*.xml"
    
    # Exclude third-party or vendored code
    - "**/third_party/**"
    - "**/vendor/**"
  
  comment: on-failure

# Dependency license configuration
dependency:
  files:
    - requirements.txt
    - setup.py
    - pyproject.toml
