openapi: 3.0.0
info:
  title: AMPEL360 Model API
  version: 1.0.0
  description: API specification for neural network model interfaces
paths:
  /models/{model_id}/predict:
    post:
      summary: Execute model inference
      parameters:
        - name: model_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                inputs:
                  type: object
                config:
                  type: object
      responses:
        '200':
          description: Successful prediction
          content:
            application/json:
              schema:
                type: object
                properties:
                  prediction:
                    type: object
                  confidence:
                    type: number
