# Copyright 2025 AMPEL360 Project Contributors
# Licensed under the Apache License, Version 2.0

model_card:
  name: "Event Segmenter"
  version: "1.0"
  model_id: "95-20-31-A-103"
  subsystem: "95-20-31 NN_Recording_Systems"
  status: "development"
  created_date: "2025-11-18"
  last_updated: "2025-11-18"
  
  description:
    summary: "CNN + Bi-LSTM with CRF for detecting and segmenting events in CVR/FDR recordings"
    purpose: "Automate identification of relevant recording intervals for efficient analysis"
    use_case: "Post-flight event detection and segmentation for AMPEL360 BWB H₂ Hy-E"
    
architecture:
  type: "CNN + Bi-LSTM + Attention + CRF"
  framework: "PyTorch 2.1"
  input_features: "Multi-modal (audio embeddings + FDR parameters)"
  
  layers:
    - type: "Feature Fusion"
      description: "Combines audio and FDR features"
    - type: "CNN Encoder"
      filters: [64, 128, 256]
      kernel_size: 3
      description: "Extracts local event patterns"
    - type: "Bi-LSTM"
      units: 128
      layers: 2
      description: "Captures temporal context"
    - type: "Attention"
      description: "Focuses on event-relevant features"
    - type: "CRF Output Layer"
      num_tags: 10
      description: "Event boundary and classification"
      
  total_parameters: 2500000
  trainable_parameters: 2500000
  model_size_mb: 95
  format: "ONNX"
  
training:
  dataset:
    name: "95-20-31-603_Event_Segments_Annotated"
    source: "15,000+ hours labeled recordings"
    hours: 15000
    events: 3000
    split:
      train: 0.75
      validation: 0.15
      test: 0.10
      
  hyperparameters:
    optimizer: "AdamW"
    learning_rate: 0.0001
    batch_size: 32
    epochs: 50
    
  training_time:
    duration_hours: 48
    hardware: "4x NVIDIA A100 GPU"
    
  loss_function:
    name: "BCE + CRF Loss"
    
performance:
  metrics:
    segmentation_accuracy:
      test: 0.96
      description: "IoU with ground truth"
    boundary_precision:
      test: 2.0
      unit: "seconds"
    event_detection_recall:
      test: 0.97
    processing_speed:
      test: 10.0
      unit: "x real-time"
      
  inference:
    latency_ms:
      mean: 50
      p95: 75
    throughput_hz: 1
    memory_mb: 800
    
certification:
  dal_level: "C"
  failure_condition: "Hazardous"
  compliance:
    - standard: "DO-178C"
      level: "C"
      status: "In Progress"
      url: "https://www.rtca.org/product/do-178c/"
    - standard: "EASA SC-AI"
      status: "In Progress"
      url: "https://www.easa.europa.eu/en/document-library/general-publications/special-condition-sc-ai"
      
document_control:
  version: "1.0"
  status: "DEVELOPMENT"
  last_updated: "2025-11-18"
  ai_assistance:
    used: true
    tools: ["GitHub Copilot"]
    prompted_by: "Amedeo Pelliccia"
