# Enterprise Systems Integration

openapi: 3.0.0
info:
  title: AMPEL360 DPP Enterprise Integration API
  version: 2.0.0
  description: Integration APIs for enterprise systems (ERP, Document Management, Regulatory Reporting)

servers:
  - url: https://api.ampel360.aero/v1
    description: Production API
  - url: https://api-staging.ampel360.aero/v1
    description: Staging API

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://auth.ampel360.aero/oauth/token
          scopes:
            read:dpp: Read DPP data
            write:dpp: Write DPP data
            admin:dpp: Administrative access

paths:
  /dpp/{dppId}:
    get:
      summary: Get DPP by ID
      parameters:
        - name: dppId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: DPP retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DPP'
    
  /dpp/{dppId}/erp-sync:
    post:
      summary: Synchronize DPP with ERP system
      parameters:
        - name: dppId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                erpSystem:
                  type: string
                  enum: [SAP, Oracle, Microsoft]
                syncType:
                  type: string
                  enum: [full, incremental]
      responses:
        '200':
          description: Sync successful

  /dpp/{dppId}/regulatory-report:
    post:
      summary: Generate regulatory report
      parameters:
        - name: dppId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                reportType:
                  type: string
                  enum: [EASA, FAA, Environmental]
                period:
                  type: object
                  properties:
                    from:
                      type: string
                      format: date
                    to:
                      type: string
                      format: date
      responses:
        '200':
          description: Report generated
          content:
            application/pdf:
              schema:
                type: string
                format: binary

  /integration/webhook:
    post:
      summary: Webhook endpoint for external systems
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                event:
                  type: string
                data:
                  type: object
      responses:
        '200':
          description: Webhook processed

components:
  schemas:
    DPP:
      type: object
      properties:
        dppId:
          type: string
        assetType:
          type: string
        status:
          type: string
        blockchainHash:
          type: string

security:
  - ApiKeyAuth: []
  - OAuth2: [read:dpp]
