#!/usr/bin/env python3
"""
Loop Packet Generator

This script generates a complete Loop Packet skeleton for a given BB ID,
using the templates and populating artifact-specific details.

Usage:
    python generate_loop_packet.py --bb-id 27-BB-008 --name "Active Gust Alleviation System" \
        --body-ata 27 --brain-ata 95 --dal A --brain-type ML-INF \
        --om-class "Flight Control Augmentation - Gust Load Alleviation"
"""

import argparse
import csv
import sys
from pathlib import Path
from datetime import datetime

# Import shared utilities
from loop_packet_utils import (
    get_repo_paths, validate_bb_id, format_csv_entry, CSV_COLUMNS
)


def generate_loop_packet(args):
    """Generate a complete Loop Packet skeleton."""
    
    # Validate BB ID
    if not validate_bb_id(args.bb_id):
        print(f"ERROR: BB ID '{args.bb_id}' is not valid. Must be in format ATAxx-BB-###")
        return 1
    
    # Get paths
    paths = get_repo_paths(Path(__file__).parent)
    templates_dir = paths['loops_base'] / "TEMPLATES"
    target_dir = paths['loops_base'] / args.bb_id
    
    # Check if templates exist
    if not templates_dir.exists():
        print(f"ERROR: Templates directory not found: {templates_dir}")
        return 1
    
    # Create target directory
    target_dir.mkdir(parents=True, exist_ok=True)
    print(f"Created Loop Packet directory: {target_dir}")
    
    # Template file names
    templates = [
        "LOOP_TEMPLATE.md",
        "AM_TEMPLATE.md",
        "DV_TEMPLATE.md",
        "DPP_TEMPLATE.md",
        "OM_TEMPLATE.md",
        "OAV_TEMPLATE.md",
        "DT_TEMPLATE.md"
    ]
    
    # Substitution mapping
    substitutions = {
        "<bb_id>": args.bb_id,
        "<Artifact_Name>": args.name,
        "<Body_ATA>": args.body_ata,
        "<Brain_ATA>": args.brain_ata,
        "<DAL>": args.dal,
        "<BrainType>": args.brain_type,
        "<om_class>": args.om_class,
        "YYYY-MM-DD": datetime.now().strftime("%Y-%m-%d"),
        "TEMPLATE": "DRAFT",
        "<version>": "1.0"
    }
    
    # Process each template
    generated_files = []
    for template_name in templates:
        template_path = templates_dir / template_name
        
        if not template_path.exists():
            print(f"WARNING: Template not found: {template_path}")
            continue
        
        # Read template
        with open(template_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # Apply substitutions
        for placeholder, value in substitutions.items():
            content = content.replace(placeholder, value)
        
        # Determine output filename
        artifact_type = template_name.replace("_TEMPLATE.md", "")
        output_name = f"{artifact_type}_{args.bb_id}.md"
        output_path = target_dir / output_name
        
        # Write output
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(content)
        
        generated_files.append(output_name)
        print(f"  Generated: {output_name}")
    
    # Generate CSV entry
    csv_entry = generate_csv_entry(args)
    csv_path = target_dir / f"{args.bb_id}_register_entry.csv"
    with open(csv_path, 'w', encoding='utf-8') as f:
        f.write(csv_entry)
    print(f"  Generated: {args.bb_id}_register_entry.csv (CSV register entry)")
    
    print(f"\nLoop Packet generation complete!")
    print(f"Location: {target_dir}")
    print(f"Files generated: {len(generated_files) + 1}")
    print(f"\nNext steps:")
    print(f"  1. Add the CSV entry to the main register: ASSETS/95-00-01-010-A-001_BodyBrain_Identity_Register.csv")
    print(f"  2. Populate the artifact files with actual content")
    print(f"  3. Update LOOP_{args.bb_id}.md as the circuit progresses")
    
    return 0


def generate_csv_entry(args):
    """Generate a CSV register entry for the artifact."""
    
    entry_dict = format_csv_entry(
        bb_id=args.bb_id,
        artifact_name=args.name,
        body_summary=args.body_summary,
        brain_summary=args.brain_summary,
        body_ata=args.body_ata,
        brain_ata=args.brain_ata,
        dal=args.dal,
        brain_type=args.brain_type,
        om_class=args.om_class,
        notes="Generated by Loop Packet Generator"
    )
    
    # Format as CSV
    output = []
    output.append(','.join(CSV_COLUMNS))
    output.append(','.join(entry_dict[col] for col in CSV_COLUMNS))
    
    return '\n'.join(output) + '\n'


def main():
    parser = argparse.ArgumentParser(
        description="Generate a complete Loop Packet skeleton for a BB ID",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Example:
    python generate_loop_packet.py --bb-id 27-BB-008 \\
        --name "Active Gust Alleviation System" \\
        --body-ata 27 --brain-ata 95 --dal A --brain-type ML-INF \\
        --body-summary "Control surfaces and sensors" \\
        --brain-summary "Gust load alleviation ML" \\
        --om-class "Flight Control Augmentation - Gust Load Alleviation"
        """
    )
    
    parser.add_argument('--bb-id', required=True, help='BB ID (e.g., 27-BB-008)')
    parser.add_argument('--name', required=True, help='Artifact name')
    parser.add_argument('--body-ata', required=True, help='Body ATA chapter')
    parser.add_argument('--brain-ata', required=True, help='Brain ATA chapter')
    parser.add_argument('--dal', required=True, choices=['A', 'B', 'C', 'D', 'E'], help='Design Assurance Level')
    parser.add_argument('--brain-type', required=True, help='Brain type (e.g., ML-INF, RT-CTRL, NAV)')
    parser.add_argument('--body-summary', required=True, help='Body summary (physical components)')
    parser.add_argument('--brain-summary', required=True, help='Brain summary (embedded logic)')
    parser.add_argument('--om-class', required=True, help='Operational Mission class')
    
    args = parser.parse_args()
    
    return generate_loop_packet(args)


if __name__ == '__main__':
    sys.exit(main())
