# Copyright 2025 AMPEL360 Project Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Copyright 2025 AMPEL360 Project Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

openapi: 3.1.0
info:
  title: AMPEL360 Flight Operations API
  version: 1.0.0
  description: |
    Example Flight Operations API for AMPEL360 operations systems.
    
    **IMPORTANT**: This is a non-proprietary example specification.
    No real endpoints, credentials, or operational data.
  contact:
    name: AMPEL360 API Team
    email: api-support@ampel360.example.com
  license:
    name: Example License
    url: https://example.com/license

servers:
  - url: https://api.ampel360.example.com/v1
    description: Production server (example)
  - url: https://staging-api.ampel360.example.com/v1
    description: Staging server (example)
  - url: http://localhost:8080/v1
    description: Local development

security:
  - BearerAuth: []
  - ApiKeyAuth: []

paths:
  /flights:
    get:
      summary: List flights
      description: Retrieve a paginated list of flights
      operationId: listFlights
      tags:
        - Flights
      parameters:
        - name: date
          in: query
          description: Filter by flight date (ISO 8601 format YYYY-MM-DD)
          schema:
            type: string
            format: date
            example: "2025-11-21"
        - name: status
          in: query
          description: Filter by flight status
          schema:
            $ref: '#/components/schemas/FlightStatus'
        - name: departure_airport
          in: query
          description: Filter by departure airport ICAO code
          schema:
            type: string
            pattern: '^[A-Z]{4}$'
            example: "KJFK"
        - name: page
          in: query
          description: Page number for pagination
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: per_page
          in: query
          description: Items per page
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlightListResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'
    
    post:
      summary: Create flight
      description: Create a new flight record
      operationId: createFlight
      tags:
        - Flights
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FlightCreate'
      responses:
        '201':
          description: Flight created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Flight'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /flights/{flight_id}:
    get:
      summary: Get flight by ID
      description: Retrieve a specific flight by ID
      operationId: getFlight
      tags:
        - Flights
      parameters:
        - $ref: '#/components/parameters/FlightId'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Flight'
        '404':
          $ref: '#/components/responses/NotFound'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'
    
    put:
      summary: Update flight
      description: Update an existing flight
      operationId: updateFlight
      tags:
        - Flights
      parameters:
        - $ref: '#/components/parameters/FlightId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FlightUpdate'
      responses:
        '200':
          description: Flight updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Flight'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
    
    delete:
      summary: Delete flight
      description: Delete a flight record (soft delete)
      operationId: deleteFlight
      tags:
        - Flights
      parameters:
        - $ref: '#/components/parameters/FlightId'
      responses:
        '204':
          description: Flight deleted successfully
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /flights/{flight_id}/status:
    patch:
      summary: Update flight status
      description: Update only the status of a flight
      operationId: updateFlightStatus
      tags:
        - Flights
      parameters:
        - $ref: '#/components/parameters/FlightId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - status
              properties:
                status:
                  $ref: '#/components/schemas/FlightStatus'
      responses:
        '200':
          description: Status updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Flight'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token for authentication
    
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
      description: API key for service-to-service authentication

  parameters:
    FlightId:
      name: flight_id
      in: path
      required: true
      description: Unique flight identifier
      schema:
        type: integer
        format: int64
        example: 12345

  schemas:
    Flight:
      type: object
      required:
        - id_flight
        - flight_number
        - flight_date
        - departure_airport_icao
        - arrival_airport_icao
        - scheduled_departure_utc
        - scheduled_arrival_utc
        - status
      properties:
        id_flight:
          type: integer
          format: int64
          description: Unique flight identifier
          example: 12345
        uuid_flight:
          type: string
          format: uuid
          description: UUID for external reference
          example: "550e8400-e29b-41d4-a716-446655440000"
        flight_number:
          type: string
          pattern: '^[A-Z0-9]{2,3}[0-9]{3,4}$'
          description: Flight number
          example: "AA123"
        flight_date:
          type: string
          format: date
          description: Flight date
          example: "2025-11-21"
        aircraft_registration:
          type: string
          description: Aircraft registration
          example: "N12345"
        departure_airport_icao:
          type: string
          pattern: '^[A-Z]{4}$'
          description: Departure airport ICAO code
          example: "KJFK"
        arrival_airport_icao:
          type: string
          pattern: '^[A-Z]{4}$'
          description: Arrival airport ICAO code
          example: "EGLL"
        scheduled_departure_utc:
          type: string
          format: date-time
          description: Scheduled departure time (UTC)
          example: "2025-11-21T14:30:00Z"
        scheduled_arrival_utc:
          type: string
          format: date-time
          description: Scheduled arrival time (UTC)
          example: "2025-11-21T22:45:00Z"
        actual_departure_utc:
          type: string
          format: date-time
          nullable: true
          description: Actual departure time (UTC)
          example: "2025-11-21T14:35:00Z"
        actual_arrival_utc:
          type: string
          format: date-time
          nullable: true
          description: Actual arrival time (UTC)
          example: "2025-11-21T22:50:00Z"
        status:
          $ref: '#/components/schemas/FlightStatus'
        fuel_planned_kg:
          type: number
          format: float
          minimum: 0
          description: Planned fuel in kilograms
          example: 18500.50
        passengers_count:
          type: integer
          minimum: 0
          description: Number of passengers
          example: 180
        ts_created_utc:
          type: string
          format: date-time
          description: Record creation timestamp
          example: "2025-11-20T10:00:00Z"
        ts_updated_utc:
          type: string
          format: date-time
          description: Record last updated timestamp
          example: "2025-11-21T14:35:00Z"

    FlightCreate:
      type: object
      required:
        - flight_number
        - flight_date
        - departure_airport_icao
        - arrival_airport_icao
        - scheduled_departure_utc
        - scheduled_arrival_utc
      properties:
        flight_number:
          type: string
          pattern: '^[A-Z0-9]{2,3}[0-9]{3,4}$'
          example: "AA123"
        flight_date:
          type: string
          format: date
          example: "2025-11-21"
        aircraft_registration:
          type: string
          example: "N12345"
        departure_airport_icao:
          type: string
          pattern: '^[A-Z]{4}$'
          example: "KJFK"
        arrival_airport_icao:
          type: string
          pattern: '^[A-Z]{4}$'
          example: "EGLL"
        scheduled_departure_utc:
          type: string
          format: date-time
          example: "2025-11-21T14:30:00Z"
        scheduled_arrival_utc:
          type: string
          format: date-time
          example: "2025-11-21T22:45:00Z"
        fuel_planned_kg:
          type: number
          format: float
          minimum: 0
          example: 18500.50
        passengers_count:
          type: integer
          minimum: 0
          example: 180

    FlightUpdate:
      type: object
      properties:
        actual_departure_utc:
          type: string
          format: date-time
          nullable: true
          example: "2025-11-21T14:35:00Z"
        actual_arrival_utc:
          type: string
          format: date-time
          nullable: true
          example: "2025-11-21T22:50:00Z"
        status:
          $ref: '#/components/schemas/FlightStatus'
        fuel_actual_kg:
          type: number
          format: float
          minimum: 0
          example: 18400.75
        passengers_count:
          type: integer
          minimum: 0
          example: 175

    FlightStatus:
      type: string
      enum:
        - SCHEDULED
        - BOARDING
        - DEPARTED
        - IN_FLIGHT
        - ARRIVED
        - CANCELLED
        - DELAYED
      description: Flight status
      example: "SCHEDULED"

    FlightListResponse:
      type: object
      required:
        - data
        - pagination
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Flight'
        pagination:
          $ref: '#/components/schemas/Pagination'

    Pagination:
      type: object
      required:
        - page
        - per_page
        - total_items
        - total_pages
      properties:
        page:
          type: integer
          example: 1
        per_page:
          type: integer
          example: 20
        total_items:
          type: integer
          example: 150
        total_pages:
          type: integer
          example: 8

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: Error code
          example: "VALIDATION_ERROR"
        message:
          type: string
          description: Human-readable error message
          example: "Invalid flight number format"
        details:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
                example: "flight_number"
              issue:
                type: string
                example: "Must match pattern [A-Z0-9]{2,3}[0-9]{3,4}"
        request_id:
          type: string
          format: uuid
          description: Unique request identifier for tracing
          example: "550e8400-e29b-41d4-a716-446655440000"

  responses:
    BadRequest:
      description: Bad request - invalid input
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    
    Unauthorized:
      description: Unauthorized - authentication required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    
    Conflict:
      description: Conflict - resource already exists
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

tags:
  - name: Flights
    description: Flight operations management

# Document Control
# Generated with the assistance of AI (GitHub Copilot), prompted by Amedeo Pelliccia
# Status: DRAFT – Subject to human review and approval
# Repository: AMPEL360-BWB-H2-Hy-E
# Last AI update: 2025-11-21
